/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Cliente;

import java.io.*;
import java.net.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author pablo
 */
public class IU_LoginRegistro extends javax.swing.JPanel {
    
    //Creamos una variable que relaciona este panel con el Frame que lo contiene
    private JFrame parentFrame;
    
    Socket Login = null;
    DataOutputStream out = null;
    DataInputStream in = null;
    String user;
    String password;

    private String[] usuariosConectados;
        
    public IU_LoginRegistro(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        this.setVisible(true);
        
    }
    
    public void setParentFrame(JFrame parentFrame) {
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        labelTitulo = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        textFieldUsuario = new javax.swing.JTextField();
        textFieldContrasena = new javax.swing.JTextField();
        labelError = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelTitulo.setText("TIC-TAC-TOE");

        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.setMaximumSize(new java.awt.Dimension(73, 23));
        btnLogin.setMinimumSize(new java.awt.Dimension(73, 23));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        labelUsuario.setText("Usuario");

        labelContrasena.setText("Contraseña");

        textFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsuarioActionPerformed(evt);
            }
        });

        textFieldContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContrasenaActionPerformed(evt);
            }
        });

        labelError.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        labelError.setForeground(java.awt.Color.red);
        labelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContrasena))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldUsuario)
                    .addComponent(textFieldContrasena))
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContrasena)
                    .addComponent(textFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        try {   
            comunicacionLogin( "Registro");
        } catch (IOException ex) {
            Logger.getLogger(IU_LoginRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            comunicacionLogin("Login");
        } catch (IOException ex) {
            Logger.getLogger(IU_LoginRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void textFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsuarioActionPerformed

    private void textFieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldContrasenaActionPerformed
    public void comunicacionLogin(String opcion) throws IOException{
        user = textFieldUsuario.getText();
        password = textFieldContrasena.getText();
        
        InetAddress serverAddress = InetAddress.getLocalHost();
        Login = new Socket(serverAddress, 6789);
        
        out = new DataOutputStream(Login.getOutputStream());
        in = new DataInputStream(Login.getInputStream());
        
        String respuestaServer = in.readUTF();
        System.out.println(respuestaServer);
        
        if(respuestaServer.equals("comunciacion_establecida")){
            out.writeUTF(opcion);
            out.writeUTF(user);
            out.writeUTF(password);
            
            respuestaServer = in.readUTF();
            System.out.println(respuestaServer);
            if(respuestaServer.equals("fallo_login")){
                labelError.setText("Usuario no encontrado o datos erróneos.");
            }
            if(respuestaServer.equals("fallo_registro")){
                labelError.setText("Usuario ya registrado.");
            }
            if(respuestaServer.equals("login_correcto")){
                labelError.setText("");
                //Recibir lista de usuarios del broadCast contando conque el ultimo usuario nunca va a ser Fin
                String users = in.readUTF();
                usuariosConectados = users.split(",");
                String fin = in.readUTF();
                openMainMenu();
                
                if (parentFrame != null) {
                    parentFrame.dispose();
                }
                
            }
               
        } else {
            labelError.setText("Comunicación con el servidor no establecida.");
            out.close();
            in.close();
            Login.close();
        }
    }
    
    private void openMainMenu(){
        // try{
        //     out.close();
        //     in.close();
        //     Login.close();
        // } catch (IOException e){
        //     e.printStackTrace();
        // }
        
        parentFrame.dispose();
        PracticaFinalMTPA.iniciarMenu(Login, user, usuariosConectados);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTextField textFieldContrasena;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
